name: "supreme_ai_image_generator"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    volumes:
      - .:/app:cached
    working_dir: /app
    ports:
      - "${HOST_PORT}:3000"
    command: bundle exec rails s
    env_file:
      - .env
    depends_on:
      - worker

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: worker
    volumes:
      - .:/app:cached
    working_dir: /app
    command: bundle exec sidekiq
    env_file:
      - .env
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
